# Generated by Django 4.1.6 on 2023-03-17 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('qty_metrics', models.CharField(blank=True, default=None, max_length=100)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='pics')),
                ('manufacturer', models.CharField(max_length=100)),
                ('product_category', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('shop_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('Retailer', 'Retailer'), ('Distributor', 'Distributor')], max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapi.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapi.user_details')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapi.user_details'),
        ),
        migrations.CreateModel(
            name='orders_transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, default=None, max_length=200)),
                ('distributor', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('payment_id', models.CharField(blank=True, default=None, max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapi.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='orders_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, default=None, max_length=100)),
                ('distributor', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('delivery_status', models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Delivery In Process', 'Delivery In Process'), ('Order Delivered', 'Order Delivered')], max_length=50)),
                ('amount_paid', models.BooleanField(default=False)),
                ('payment_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapi.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapi.user_details')),
            ],
        ),
    ]
