# Generated by Django 4.1.6 on 2023-03-20 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_details',
            old_name='is_cancelled',
            new_name='is_delivered',
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('its_id', models.CharField(max_length=200)),
                ('complaint_on', models.CharField(choices=[('Product', 'Product'), ('Orders', 'Orders'), ('Payment', 'Payment')], max_length=50)),
                ('complaint_book_date', models.DateTimeField(auto_now_add=True)),
                ('complaint_details', models.CharField(max_length=200)),
                ('is_complaint_closed', models.BooleanField(default=False)),
                ('reply', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('complaint_complete_date', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor', to='shopapi.user_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to='shopapi.user_details')),
            ],
        ),
    ]
